flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- binary-0.8.2.1
- binary-ieee754-0.1.0.0
- binary-parsers-0.2.3.0
- bytestring-builder-0.10.8.1.0
- integer-logarithms-1.0.1
- io-streams-1.3.6.1
- mysql-0.1.0.0
- mysql-haskell-0.8.0.0
- primitive-0.6.2.0
- scientific-0.3.4.11
- tcp-streams-0.6.0.0
- transformers-0.5.4.0
- vector-0.12.0.1
- wire-streams-0.1.1.0
- word24-2.0.1
resolver: lts-6.11
